"""durable inbox

Revision ID: 916f93cc4c0a
Revises: cf9a19f4fafd
Create Date: 2026-09-25 14:16:23.179667
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "916f93cc4c0a"
down_revision = "cf9a19f4fafd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_key", sa.String(length=250), nullable=False),
        sa.Column("event_name", sa.String(length=80), nullable=True),
        sa.Column("house_id", sa.UUID(), nullable=True),
        sa.Column("raw_update", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized_event", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_events")),
        sa.UniqueConstraint("source", "source_key", name=op.f("uq_inbox_events_source_source_key")),
    )
    op.create_index(
        "ix_inbox_events_status_received", "inbox_events", ["status", "received_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inbox_events_status_received", table_name="inbox_events")
    op.drop_table("inbox_events")
    # ### end Alembic commands ###
