"""core house registry

Revision ID: cf9a19f4fafd
Revises:
Create Date: 2026-09-25 14:04:07.337094
"""

import sqlalchemy as sa
from alembic import op

revision = "cf9a19f4fafd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "houses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("max_chat_id", sa.String(length=40), nullable=True),
        sa.Column("demo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_houses")),
        sa.UniqueConstraint("max_chat_id", name=op.f("uq_houses_max_chat_id")),
    )
    op.create_table(
        "residents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("max_user_id", sa.String(length=40), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("dm_reachable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_residents")),
        sa.UniqueConstraint("max_user_id", name=op.f("uq_residents_max_user_id")),
    )
    op.create_table(
        "apartments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("house_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=False),
        sa.Column("entrance", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.CheckConstraint("entrance > 0", name=op.f("ck_apartments_entrance_positive")),
        sa.CheckConstraint("floor >= 0", name=op.f("ck_apartments_floor_nonnegative")),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
            name=op.f("fk_apartments_house_id_houses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apartments")),
        sa.UniqueConstraint(
            "house_id", "entrance", "number", name=op.f("uq_apartments_house_id_entrance_number")
        ),
        sa.UniqueConstraint("id", "house_id", name=op.f("uq_apartments_id_house_id")),
    )
    op.create_table(
        "risers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("house_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"], ["houses.id"], name=op.f("fk_risers_house_id_houses"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risers")),
        sa.UniqueConstraint(
            "house_id", "kind", "label", name=op.f("uq_risers_house_id_kind_label")
        ),
        sa.UniqueConstraint("id", "house_id", name=op.f("uq_risers_id_house_id")),
    )
    op.create_table(
        "apartment_risers",
        sa.Column("house_id", sa.UUID(), nullable=False),
        sa.Column("apartment_id", sa.UUID(), nullable=False),
        sa.Column("riser_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["apartment_id", "house_id"],
            ["apartments.id", "apartments.house_id"],
            name=op.f("fk_apartment_risers_apartment_id_house_id_apartments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["riser_id", "house_id"],
            ["risers.id", "risers.house_id"],
            name=op.f("fk_apartment_risers_riser_id_house_id_risers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "house_id", "apartment_id", "riser_id", name=op.f("pk_apartment_risers")
        ),
    )
    op.create_table(
        "residencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("house_id", sa.UUID(), nullable=False),
        sa.Column("apartment_id", sa.UUID(), nullable=False),
        sa.Column("resident_id", sa.UUID(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("adult", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name=op.f("ck_residencies_valid_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id", "house_id"],
            ["apartments.id", "apartments.house_id"],
            name=op.f("fk_residencies_apartment_id_house_id_apartments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resident_id"],
            ["residents.id"],
            name=op.f("fk_residencies_resident_id_residents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_residencies")),
        sa.UniqueConstraint(
            "house_id",
            "apartment_id",
            "resident_id",
            "valid_from",
            name=op.f("uq_residencies_house_id_apartment_id_resident_id_valid_from"),
        ),
    )
    op.create_index(
        "ix_residencies_house_status",
        "residencies",
        ["house_id", "confirmed", "adult"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_residencies_house_status", table_name="residencies")
    op.drop_table("residencies")
    op.drop_table("apartment_risers")
    op.drop_table("risers")
    op.drop_table("apartments")
    op.drop_table("residents")
    op.drop_table("houses")
    # ### end Alembic commands ###
